# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  cli:
    container_name: cli
    image: registry.cn-hangzhou.aliyuncs.com/timechainer/hyperledger/fabric-tools:1.4.8
    tty: true
    network_mode: host
    environment:
      - GOPATH=/opt/gopath
      - GODEBUG=netdns=go
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_ID=cli
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bridge
      - CORE_PEER_ADDRESS=peer0.org1.cluster.hlyardman1:443
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_LOCALMSPTYPE=bccsp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto-config/peerOrganizations/org1.cluster.hlyardman1/peers/peer0.org1.cluster.hlyardman1/tls/client.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto-config/peerOrganizations/org1.cluster.hlyardman1/peers/peer0.org1.cluster.hlyardman1/tls/client.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto-config/peerOrganizations/org1.cluster.hlyardman1/peers/peer0.org1.cluster.hlyardman1/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/crypto-config/peerOrganizations/org1.cluster.hlyardman1/users/Admin@org1.cluster.hlyardman1/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c 'sleep 1000000'
    volumes:
      - ../chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      -  /opt/share/hlyardman1/cluster/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/crypto-config
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    extra_hosts:
      - "orderer0.cluster.hlyardman1:192.168.49.2"
      - "orderer1.cluster.hlyardman1:192.168.49.2"
      - "orderer2.cluster.hlyardman1:192.168.49.2"
      - "peer0.org1.cluster.hlyardman1:192.168.49.2"
      - "peer0.org2.cluster.hlyardman1:192.168.49.2"
